set_property PACKAGE_PIN W4 [get_ports {sel_frq_meter[3]}]
set_property PACKAGE_PIN V4 [get_ports {sel_frq_meter[2]}]
set_property PACKAGE_PIN U4 [get_ports {sel_frq_meter[1]}]
set_property PACKAGE_PIN U2 [get_ports {sel_frq_meter[0]}]
set_property PACKAGE_PIN W7 [get_ports a]
set_property PACKAGE_PIN W6 [get_ports b]
set_property PACKAGE_PIN U8 [get_ports c]
set_property PACKAGE_PIN V8 [get_ports d]
set_property PACKAGE_PIN U5 [get_ports e]
set_property PACKAGE_PIN V5 [get_ports f]
set_property PACKAGE_PIN U7 [get_ports g]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_frq_meter[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_frq_meter[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_frq_meter[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports e]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_frq_meter[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports f]
set_property IOSTANDARD LVCMOS33 [get_ports g]
set_property IOSTANDARD LVCMOS33 [get_ports clk_frq_meter]
set_property PACKAGE_PIN W5 [get_ports clk_frq_meter]

set_property IOSTANDARD LVCMOS33 [get_ports signal_frq_meter]
set_property PACKAGE_PIN J1 [get_ports signal_frq_meter]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets signal_frq_meter_IBUF]

